### ISSUE TITLE
Po wybraniu Polski lub Globalnych trzeba zresetować lustro żeby zmiany się pobrały.

### ISSUE THREAD

**Issue by chriswieczorek** [AmebyDevGroup/BlackMirror_Client#13]
Po wybraniu w ws leci tylko jedna konkretna dana. 
Jeżeli była jedna pokazana a dostaniesz dwie to jest okej. Jeżeli były dwie a ma być jedna to nie ukrywasz tej jednej.

**Comment by WerVa** [comment]
@jlorc  poprawił
